// Generated by scripts/presentation.mjs; edit the canonical JSON instead.
package com.remilo.alarm.presentation

object AtmosphereTokens {
  data class Roles(val canvas: Long, val surface: Long, val onSurface: Long, val onSurfaceVariant: Long, val primary: Long, val onPrimary: Long, val container: Long, val outline: Long, val error: Long, val warning: Long, val success: Long, val disabledSurface: Long, val disabledInk: Long, val inverseSurface: Long, val inverseInk: Long, val inverseAction: Long, val focus: Long, val selectedSurface: Long, val selectedInk: Long, val primaryPressed: Long, val onPrimaryPressed: Long, val secondaryPressed: Long, val onSecondaryPressed: Long, val dangerSurface: Long, val dangerInk: Long, val dangerPressed: Long, val headerInk: Long, val headerScrim: Long, val headerScrimAlpha: Float, val drawableName: String, val heroX: Float, val heroY: Float, val compactX: Float, val compactY: Float)
  fun colors(scene: String, brightness: String): Roles = when ("$scene-$brightness") {
      "sunrise-light" -> Roles(0xFFFFF8F2L, 0xFFFFFFFFL, 0xFF251E1AL, 0xFF66564BL, 0xFFA83F0CL, 0xFFFFFFFFL, 0xFFF9E9DDL, 0xFF8D7869L, 0xFFA8231BL, 0xFF774900L, 0xFF17603AL, 0xFFE3E1DFL, 0xFF55514EL, 0xFF252B34L, 0xFFF8FAFFL, 0xFFB5CEFFL, 0xFFA83F0CL, 0xFFF9E9DDL, 0xFFA83F0CL, 0xFFA83F0CL, 0xFFFFFFFFL, 0xFFF9E9DDL, 0xFFA83F0CL, 0xFFA8231BL, 0xFFFFFFFFL, 0xFFB13932L, 0xFF172331L, 0xFFFFFFFFL, 0.54f, "remilo_scene_sunrise_light_v1", 0.5f, 0.500534f, 0.5f, 0.460321f)
      "sunrise-dark" -> Roles(0xFF191716L, 0xFF282422L, 0xFFF9EFE7L, 0xFFC8B8ABL, 0xFFFFB77FL, 0xFF442008L, 0xFF3A2D25L, 0xFFA38A78L, 0xFFFFB4ABL, 0xFFF3CC83L, 0xFF87D5A3L, 0xFF363D48L, 0xFFC5C9D2L, 0xFFE8EDF5L, 0xFF202A39L, 0xFF244D9AL, 0xFFFFB77FL, 0xFF3A2D25L, 0xFFFFB77FL, 0xFFFFB77FL, 0xFF442008L, 0xFF3A2D25L, 0xFFFFB77FL, 0xFFFFB4ABL, 0xFF690005L, 0xFFF0A29AL, 0xFFFFFFFFL, 0xFF000000L, 0.54f, "remilo_scene_sunrise_dark_v1", 0.5f, 0.500534f, 0.5f, 0.460321f)
      "sky-light" -> Roles(0xFFF3F8FDL, 0xFFFFFFFFL, 0xFF172331L, 0xFF4E6173L, 0xFF175BC4L, 0xFFFFFFFFL, 0xFFE4EFFAL, 0xFF738599L, 0xFFA8231BL, 0xFF774900L, 0xFF17603AL, 0xFFE3E1DFL, 0xFF55514EL, 0xFF252B34L, 0xFFF8FAFFL, 0xFFB5CEFFL, 0xFF175BC4L, 0xFFE4EFFAL, 0xFF175BC4L, 0xFF175BC4L, 0xFFFFFFFFL, 0xFFE4EFFAL, 0xFF175BC4L, 0xFFA8231BL, 0xFFFFFFFFL, 0xFFB13932L, 0xFF172331L, 0xFFFFFFFFL, 0.54f, "remilo_scene_sky_light_v1", 0.5f, 0.500534f, 0.5f, 0.460321f)
      "sky-dark" -> Roles(0xFF141D27L, 0xFF202C38L, 0xFFEAF2FCL, 0xFFB6C6D8L, 0xFF9CCAFFL, 0xFF092D53L, 0xFF2B3D51L, 0xFF829BB6L, 0xFFFFB4ABL, 0xFFF3CC83L, 0xFF87D5A3L, 0xFF363D48L, 0xFFC5C9D2L, 0xFFE8EDF5L, 0xFF202A39L, 0xFF244D9AL, 0xFF9CCAFFL, 0xFF2B3D51L, 0xFF9CCAFFL, 0xFF9CCAFFL, 0xFF092D53L, 0xFF2B3D51L, 0xFF9CCAFFL, 0xFFFFB4ABL, 0xFF690005L, 0xFFF0A29AL, 0xFFFFFFFFL, 0xFF000000L, 0.54f, "remilo_scene_sky_dark_v1", 0.5f, 0.500534f, 0.5f, 0.460321f)
      "evening-light" -> Roles(0xFFFFF6FAL, 0xFFFFFFFFL, 0xFF2B1D2AL, 0xFF6D5265L, 0xFF7F3968L, 0xFFFFFFFFL, 0xFFF3E5EEL, 0xFF937A8BL, 0xFFA8231BL, 0xFF774900L, 0xFF17603AL, 0xFFE3E1DFL, 0xFF55514EL, 0xFF252B34L, 0xFFF8FAFFL, 0xFFB5CEFFL, 0xFF7F3968L, 0xFFF3E5EEL, 0xFF7F3968L, 0xFF7F3968L, 0xFFFFFFFFL, 0xFFF3E5EEL, 0xFF7F3968L, 0xFFA8231BL, 0xFFFFFFFFL, 0xFFB13932L, 0xFF172331L, 0xFFFFFFFFL, 0.54f, "remilo_scene_evening_light_v1", 0.5f, 0.500534f, 0.5f, 0.460321f)
      "evening-dark" -> Roles(0xFF201820L, 0xFF302330L, 0xFFFAEDF6L, 0xFFD3BACDL, 0xFFEEB1D6L, 0xFF44203AL, 0xFF432E41L, 0xFFAD8CA5L, 0xFFFFB4ABL, 0xFFF3CC83L, 0xFF87D5A3L, 0xFF363D48L, 0xFFC5C9D2L, 0xFFE8EDF5L, 0xFF202A39L, 0xFF244D9AL, 0xFFEEB1D6L, 0xFF432E41L, 0xFFEEB1D6L, 0xFFEEB1D6L, 0xFF44203AL, 0xFF432E41L, 0xFFEEB1D6L, 0xFFFFB4ABL, 0xFF690005L, 0xFFF0A29AL, 0xFFFFFFFFL, 0xFF000000L, 0.54f, "remilo_scene_evening_dark_v1", 0.5f, 0.500534f, 0.5f, 0.460321f)
      "night-light" -> Roles(0xFFF2F6FDL, 0xFFFFFFFFL, 0xFF17243CL, 0xFF52617BL, 0xFF294F91L, 0xFFFFFFFFL, 0xFFE5ECFAL, 0xFF7B88A4L, 0xFFA8231BL, 0xFF774900L, 0xFF17603AL, 0xFFE3E1DFL, 0xFF55514EL, 0xFF252B34L, 0xFFF8FAFFL, 0xFFB5CEFFL, 0xFF294F91L, 0xFFE5ECFAL, 0xFF294F91L, 0xFF294F91L, 0xFFFFFFFFL, 0xFFE5ECFAL, 0xFF294F91L, 0xFFA8231BL, 0xFFFFFFFFL, 0xFFB13932L, 0xFFFFFFFFL, 0xFF000000L, 0.54f, "remilo_scene_night_light_v2", 0.5f, 0.500534f, 0.5f, 0.43016f)
      "night-dark" -> Roles(0xFF121B2AL, 0xFF1F2B3CL, 0xFFECF1FCL, 0xFFB8C5DDL, 0xFFB2C3FFL, 0xFF182B53L, 0xFF2B3A53L, 0xFF869ABCL, 0xFFFFB4ABL, 0xFFF3CC83L, 0xFF87D5A3L, 0xFF363D48L, 0xFFC5C9D2L, 0xFFE8EDF5L, 0xFF202A39L, 0xFF244D9AL, 0xFFB2C3FFL, 0xFF2B3A53L, 0xFFB2C3FFL, 0xFFB2C3FFL, 0xFF182B53L, 0xFF2B3A53L, 0xFFB2C3FFL, 0xFFFFB4ABL, 0xFF690005L, 0xFFF0A29AL, 0xFFFFFFFFL, 0xFF000000L, 0.54f, "remilo_scene_night_dark_v2", 0.5f, 0.500534f, 0.5f, 0.43016f)
      else -> colors("night", "light")
  }
  const val home = 200
  const val secondary = 96
  const val toolbar = 56
  const val gutter = 16
  const val radius = 16
  const val target = 48
  const val action = 56
  const val nativeSingle = 64
  const val nativeMember = 56
  const val typeDisplay = 32
  const val typeTitle = 24
  const val typeAppBar = 22
  const val typeHeading = 18
  const val typeBody = 16
  const val typeSupporting = 14
  const val typeLabel = 14
  const val spaceXs = 4
  const val spaceSm = 8
  const val spaceMd = 12
  const val spaceGutter = 16
  const val spaceLg = 24
  const val spaceXl = 32
  const val shapeField = 16
  const val shapeGroup = 16
  const val shapeSheet = 24
  const val shapeAction = 16
  const val shapeRoundAction = 999
}
