/** Dedicated P02 exporter. Never generates or touches icon/P01 submission files. */
import assert from 'node:assert/strict';
import { Buffer } from 'node:buffer';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { dirname, resolve, sep } from 'node:path';
import { validateCatalog, colorRoles } from './lib/p02-catalog.mjs';
const root = resolve(import.meta.dirname, '..');
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const path = name => {
  assert.ok(typeof name === 'string');
  const value = resolve(root, name); assert.ok(value.startsWith(root + sep), 'Path outside workspace'); return value;
};
const mode = process.argv[2];
if (mode === '--help') {
  console.log('node scripts/p02-export.mjs --export|--check [sharp-package-path]\nDeterministic P02 static TS/Kotlin/PNG export. --check is read-only. No icons or owner approvals.'); process.exit(0);
}
assert.ok(['--export', '--check'].includes(mode) && process.argv.length <= 4, 'Choose --export, --check or --help.');
const sharp = createRequire(import.meta.url)(process.argv[3] || 'sharp');
const input = await readFile(path('docs/design/p02/catalog.json'));
const catalog = validateCatalog(JSON.parse(input));
assert.equal(sharp.versions.sharp, catalog.export.sharpVersion, 'Pinned Sharp runtime');
const outputs = new Map();
const assetRecords = [];
for (const asset of catalog.assets) {
  const source = await readFile(path(asset.source.path));
  assert.equal(hash(source), asset.source.sha256, 'Source hash');
  const metadata = await sharp(source).metadata();
  assert.equal(metadata.width, asset.source.width); assert.equal(metadata.height, asset.source.height);
  assert.ok(metadata.hasAlpha, 'Preserve real source alpha');
  const width = Math.min(metadata.width, 1440, Math.floor(Math.sqrt(2_000_000 * metadata.width / metadata.height)));
  const height = Math.round(width * metadata.height / metadata.width);
  let pipeline = sharp(source).resize(width, height, { fit: 'fill', withoutEnlargement: true, kernel: 'lanczos3' });
  const mul = asset.treatment.multiplier;
  if (mul.some(n => n !== 1)) pipeline = pipeline.recomb([[mul[0],0,0],[0,mul[1],0],[0,0,mul[2]]]);
  const png = await pipeline.png({ compressionLevel: 9, adaptiveFiltering: false, palette: false }).toBuffer();
  assert.ok(png.length <= 2 * 1024 * 1024, `${asset.id} exceeds image budget`);
  assert.ok(width * height <= 2_000_000);
  const rn = `assets/foundations/${asset.id}.png`;
  // Unapproved sample scenery is debug-only on Android and opt-in on RN.
  const native = `modules/remilo-alarm/android/src/${catalog.stage === 'sample' ? 'debug' : 'main'}/res/drawable-nodpi/${asset.id}.png`;
  outputs.set(rn, png); outputs.set(native, png);
  assetRecords.push({ id: asset.id, source: asset.source, treatment: asset.treatment, width, height,
    bytes: png.length, sha256: hash(png), rn, native });
}
assert.ok(assetRecords.reduce((sum, a) => sum + a.bytes, 0) <= 24 * 1024 * 1024, 'Unique shipped catalog budget');
const data = { schemaVersion: catalog.schemaVersion, revision: catalog.revision, stage: catalog.stage,
  paletteIds: catalog.paletteIds, tokens: catalog.tokens, composeMapping: catalog.composeMapping, palettes: catalog.palettes,
  assets: assetRecords.map(({id, width, height, sha256}) => ({id, width, height, sha256})) };
outputs.set('src/ui/foundations/catalog.generated.ts', Buffer.from(`// Generated by scripts/p02-export.mjs. Static values only.\nexport const foundationCatalog = ${JSON.stringify(data, null, 2)} as const;\n`));
outputs.set('verification/ui/p02-assets.generated.ts', Buffer.from(`// Generated; imported only through the opt-in review entry.\nimport type { ImageSourcePropType } from 'react-native';\nexport const p02Assets: Record<string, ImageSourcePropType> = {\n${assetRecords.map(a => `  '${a.id}': require('../../${a.rn}'),`).join('\n')}\n};\n`));
const kotlin = `// Generated by scripts/p02-export.mjs. Static values only.\npackage com.remilo.alarm.foundation\n\ninternal object FoundationCatalog {\n  const val schemaVersion = 1\n  const val revision = "${catalog.revision}"\n  const val stage = "${catalog.stage}"\n  val paletteIds = listOf(${catalog.paletteIds.map(id => `"${id}"`).join(', ')})\n  val tokens = mapOf(${Object.entries(catalog.tokens).flatMap(([group, values]) => Object.entries(values).map(([key, value]) => `"${group}.${key}" to ${value}f`)).join(', ')})\n  val composeMapping = mapOf(${Object.entries(catalog.composeMapping).map(([key, value]) => `"${key}" to "${value}"`).join(', ')})\n  val colors: Map<String, Map<String, Map<String, Long>>> = mapOf(\n${catalog.palettes.map(p => `    "${p.id}" to mapOf(${['light','dark'].map(b => `"${b}" to mapOf(${colorRoles.map(role => `"${role}" to 0xFF${p.colors[b][role].slice(1)}L`).join(', ')})`).join(', ')})`).join(',\n')}\n  )\n  val scenes = mapOf(\n${catalog.palettes.filter(p => p.id !== 'classic').map(p => ['light','dark'].map(b => `    "${p.id}/${b}" to "${p.scenes[b].assetId}"`).join(',\n')).join(',\n')}\n  )\n  val assets = mapOf(${assetRecords.map(a => `"${a.id}" to "${a.sha256}"`).join(', ')})\n}\n`;
const placements = catalog.palettes.filter(p => p.id !== 'classic').flatMap(p => ['light','dark'].flatMap(b => ['browsing','individual'].map(mode => {
  const v = p.scenes[b][mode];
  return `    "${p.id}/${b}/${mode}" to ScenePlacement("${v.edge}", listOf(${v.anchor.map(n => `${n}f`).join(', ')}), listOf(${v.quietRegion.map(n => `${n}f`).join(', ')}), ${v.heightFraction}f, ${v.maxColumnDp}f)`;
})));
const finalKotlin = kotlin.replace('  val assets =', `  val placements = mapOf(\n${placements.join(',\n')}\n  )\n  val assets =`);
outputs.set('modules/remilo-alarm/android/src/main/java/com/remilo/alarm/foundation/FoundationCatalog.generated.kt', Buffer.from(finalKotlin));
const manifest = { schemaVersion: 1, revision: catalog.revision, stage: catalog.stage, source: { path: 'docs/design/p02/catalog.json', sha256: hash(input) },
  exporter: { path: 'scripts/p02-export.mjs', sha256: hash(await readFile(path('scripts/p02-export.mjs'))) },
  validator: { path: 'scripts/lib/p02-catalog.mjs', sha256: hash(await readFile(path('scripts/lib/p02-catalog.mjs'))) },
  sharpVersion: sharp.versions.sharp, parameters: catalog.export, assets: assetRecords,
  outputs: [...outputs].map(([name, bytes]) => ({ path: name, sha256: hash(bytes), bytes: bytes.length })) };
outputs.set('docs/design/p02/export-manifest.json', Buffer.from(JSON.stringify(manifest, null, 2) + '\n'));
for (const [name, bytes] of outputs) {
  if (mode === '--check') assert.deepEqual(await readFile(path(name)), bytes, `Stale export: ${name}`);
  else { await mkdir(dirname(path(name)), { recursive: true }); await writeFile(path(name), bytes); }
}
console.log(JSON.stringify({ result: 'passed', mode, revision: catalog.revision, outputs: outputs.size,
  uniqueImageBytes: assetRecords.reduce((sum, a) => sum + a.bytes, 0), ownerApproval: false }, null, 2));
