// Deterministic presentation constants. Never regenerates Android projects or artwork.
import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(import.meta.dirname, '..');
const source = JSON.parse(fs.readFileSync(path.join(root, 'assets/atmospheres/presentation.json'), 'utf8'));
const ts = `// Generated by scripts/presentation.mjs from assets/atmospheres/presentation.json.\nexport const presentation = ${JSON.stringify(source, null, 2)} as const;\n`;
const names = ['canvas','surface','onSurface','onSurfaceVariant','primary','onPrimary','container','outline','error','warning','success','disabledSurface','disabledInk','inverseSurface','inverseInk','inverseAction'];
names.push(...Object.keys(source.roleAliases));
names.push('headerInk','headerScrim');
const pairs = Object.entries(source.pairs).map(([key,value]) => {
  const roles = {...value,...source.semantic[key.endsWith('-dark')?'dark':'light']};
  for (const [name, role] of Object.entries(source.roleAliases)) roles[name] = roles[role];
  roles.headerInk = source.header[key].ink; roles.headerScrim = source.header[key].scrim;
  return `      "${key}" -> Roles(${names.map(name=>`0xFF${roles[name].slice(1)}L`).join(', ')}, ${source.header[key].scrimAlpha}f, "${value.native}", ${value.heroFocal[0]}f, ${value.heroFocal[1]}f, ${value.compactFocal[0]}f, ${value.compactFocal[1]}f)`;
}).join('\n');
const constants = Object.entries(source.geometry).map(([name,value])=>`  const val ${name} = ${value}`);
for (const [group, prefix] of [['typography','type'],['spacing','space'],['shape','shape']]) {
  constants.push(...Object.entries(source[group]).map(([name,value])=>`  const val ${prefix}${name[0].toUpperCase()+name.slice(1)} = ${value}`));
}
const kt = `// Generated by scripts/presentation.mjs; edit the canonical JSON instead.\npackage com.remilo.alarm.presentation\n\nobject AtmosphereTokens {\n  data class Roles(${names.map(name=>`val ${name}: Long`).join(', ')}, val headerScrimAlpha: Float, val drawableName: String, val heroX: Float, val heroY: Float, val compactX: Float, val compactY: Float)\n  fun colors(scene: String, brightness: String): Roles = when ("$scene-$brightness") {\n${pairs}\n      else -> colors("night", "light")\n  }\n${constants.join('\n')}\n}\n`;
const files = [['src/ui/atmosphere.generated.ts',ts],['modules/remilo-alarm/android/src/main/java/com/remilo/alarm/presentation/AtmosphereTokens.kt',kt]];
for (const [file,value] of files) {
  const destination = path.join(root,file);
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(destination) || fs.readFileSync(destination,'utf8').replaceAll('\r\n','\n') !== value) throw new Error('Presentation constants need regeneration: '+file);
  } else { fs.mkdirSync(path.dirname(destination),{recursive:true}); fs.writeFileSync(destination,value); }
}
console.log(process.argv.includes('--check')?'Presentation constants match canonical roles/crops.':'Generated RN/native presentation constants.');
